# Generated by Django 5.0 on 2023-12-30 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productgallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_active'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['is_active'], 'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['is_active'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ['product'], 'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['caption'], 'verbose_name': 'تگ محصول', 'verbose_name_plural': 'تگ های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productvisit',
            options={'ordering': ['ip'], 'verbose_name': 'بازدید محصول', 'verbose_name_plural': 'بازدیدهای محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brands', to='product_module.productbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(max_length=200, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.CharField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='caption',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_mod_slug_678ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['short_description'], name='product_mod_short_d_d1858a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='product_mod_descrip_9fffa5_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrand',
            index=models.Index(fields=['title'], name='product_mod_title_490c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrand',
            index=models.Index(fields=['url_title'], name='product_mod_url_tit_768763_idx'),
        ),
        migrations.AddIndex(
            model_name='productbrand',
            index=models.Index(fields=['is_active'], name='product_mod_is_acti_94174f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['title'], name='product_mod_title_ec46e3_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['url_title'], name='product_mod_url_tit_fb4332_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='product_mod_is_acti_8feb27_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_delete'], name='product_mod_is_dele_84e533_idx'),
        ),
        migrations.AddIndex(
            model_name='productgallery',
            index=models.Index(fields=['product'], name='product_mod_product_5b2a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['caption'], name='product_mod_caption_4ed23d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvisit',
            index=models.Index(fields=['user'], name='product_mod_user_id_006e14_idx'),
        ),
        migrations.AddIndex(
            model_name='productvisit',
            index=models.Index(fields=['product'], name='product_mod_product_55dd60_idx'),
        ),
        migrations.AddIndex(
            model_name='productvisit',
            index=models.Index(fields=['ip'], name='product_mod_ip_b88b26_idx'),
        ),
    ]
