# Generated by Django 5.0 on 2024-01-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_text',
            field=models.TextField(verbose_name='متن درباره ما'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.TextField(verbose_name='متن کپی رایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='images/site-setting/', verbose_name='لوگو'),
        ),
    ]
