# Generated by Django 5.0 on 2024-01-17 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_alter_sitesetting_about_us_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footer_link_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footerlinkes', to='site_module.footerlinkbox', verbose_name='دسته بندی'),
        ),
    ]
