# Generated by Django 5.0 on 2024-01-07 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_date'], 'verbose_name': 'تماس با ما', 'verbose_name_plural': 'لیست تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created'], 'verbose_name': 'عکس پروفایل کاربر', 'verbose_name_plural': 'لیست عکس پروفایل کاربر'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='متن تماس با ما'),
        ),
    ]
