# Generated by Django 5.0 on 2024-01-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='متن نظر'),
        ),
    ]
